export const PLACE_CHOICE = 'PLACE_CHOICE';
export const NEW_ADDRESS_CREATING = 'NEW_ADDRESS_CREATING';
export const TABLE_ADDING = 'TABLE_ADDING';
export const CREATE_EVENT = 'CREATE_EVENT';
export const CREATE_TABLE = 'CREATE_TABLE';
export const EVENT_TYPE_SELECTION = 'EVENT_TYPE_SELECTION';
export const GAME_SELECTING = 'GAME_SELECTING';
export const PLAY_FORM = 'PLAY_FORM';